### ISSUE TITLE
Divide Party Loot/RPG Loot option

### ISSUE THREAD

**Issue by DrkMatr1984** [AlessioDP/Parties#11]
It would be awesome if you could detect who did the most damage to a mob by a player in the party and award the drops to the player who did the most damage. Another option I was thinking about doing was adding Json chat messages for "Need, Greed, and Pass" and based on what each player in the party picks, it awards the drop to the party member who wins the Roll. Up to you if you want to add it... I thought about coding an Add-on for Parties to do this rather than including it in the main plugin.

**Comment by AlessioDP** [comment]
Something like that it's already in my to-do list, but because it's not easy to code (it will changes A LOT of things) I decide to wait before develop it.
Maybe, it could be an expansion for Parties, I don't know.

I say it's big because I need to handle drops/damage/rarity items systems etc..
If you want develop it's not a problem! but you should follow the "Parties rules", that is everything need to be configurable!

**Comment by DrkMatr1984** [comment]
Yeah! No problem! I will give it a try! I actually started a Parties add-on a little bit ago for it, but haven't gotten very far(like you said "but because it's not easy to code"). I want to give it another shot tho so I'll let you know!
