### ISSUE TITLE
Feature Request: Support for Players Joining Multiple Parties

### ISSUE THREAD

**Issue by Senmo-awa** [AlessioDP/Parties#243]
I am using the Parties plugin on my Minecraft server, and I would like to request a feature enhancement. Currently, it seems that a player can only be part of one party at a time. It would be a great improvement if the plugin could support players being in multiple parties simultaneously.

This feature would be very helpful for my server, and I believe many other users would benefit from it as well.

Thank you for considering this request. I appreciate all the hard work you've put into this plugin!

**Comment by AlessioDP** [comment]
Thank you for the request, this has already been asked to me long time ago but its a too much complicated feature to handle.
It should require a full rewrite of the plugin because Parties is not meant to support a n-m relation between players and parties (command and data should be structured differently).

Unfortunately, this is not the right plugin to do what you are looking for and I do not plan to support it for now, I am sorry.
