### ISSUE TITLE
Issue with Spy format

### ISSUE THREAD

**Issue by SeruhioX** [AlessioDP/Parties#41]
The spy format when you put %message% in "spy-alerts" mixes the "party-chat" format.

That is to say, it does not show the player's message if not everything in "party-chat" with colors and so on.

**Comment by AlessioDP** [comment]
Thank you for the report, can I ask you to write here (or screenshot) what do you see and what you wanna see?

**Comment by SeDark** [comment]
This is how it looks

https://i.gyazo.com/e70da35be94a6052fac94a0bbab86e82.png

This is my configuration

https://i.gyazo.com/682f3c9ecd9cd80478d6a79feca9e035.png

Therefore I understand that it should not look like this, I updated today from a quite old version, and it did not work like that before (I understand that many things have changed)

**Comment by AlessioDP** [comment]
It is intentional, some people wanna see exactly what other parties see but with just the prefix of the spy, so that will be the same thing with every message: a broadcast message, a party message and go on.

I understand that it can be too much "complicated" too see that so I can try to rework that system to make it work better.

Let's see with future updates, right now I'm refactoring the code and it will take a while :)

**Comment by SeDark** [comment]
If I would ask you to do something in the future, since before I saw it gray to differentiate it whole but now it is not, thank you for the prompt response.

**Comment by AlessioDP** [comment]
Sure, I will certainly improve it, I just have to change how it works right now so I will be able to remove color codes to make it gray :)

**Comment by AlessioDP** [comment]
Improved with 2.6.1 ;)
